### ISSUE TITLE
Problem with dataset

### ISSUE THREAD

**Issue by opedge** [PetroWu/AutoPortraitMatting#1]
I'm trying to experiment with your implementation, but I found that there is no available dataset located here: http://xiaoyongshen.me/webpages/webpage_automatting/ (I wrote emails to Xiaoyong Shen but unfortunately he didn't answer :( ). May be you have a copy and you can share link to it? It will be very helpful.

**Comment by PetroWu** [comment]
I can't share the datasets without the author's permission. I'm sorry that the link of the dataset should be http://xiaoyongshen.me/webpage_portrait/index.html . The implementation of "Deep Automatic Portrait Matting" is under construction.
