### ISSUE TITLE
IOU

### ISSUE THREAD

**Issue by GirishaGarg** [PetroWu/AutoPortraitMatting#10]
Hi,

Can you mention the IOU that you are getting on the dataset ? It will help us to verify whether our implementation of the code is accurate or not. Also could you find ways to improve the performance ? 
Thanks.

**Comment by PetroWu** [comment]
I'm sorry I would not update this code any more because the implementation of the paper on ECCV16 can not be used to any projects (too much memory usage). So I would not go on with this task. And you can add codes of IOU by yourself.
