### ISSUE TITLE
A doubt

### ISSUE THREAD

**Issue by wanyy6** [PetroWu/AutoPortraitMatting#2]
Good job!
I'm also interested in these two paper ("Automatic Portrait Segmentation for Image Stylization" and "Deep Automatic Portrait Matting"). But I'm not sure whether the method of matting proposed in these two paper are same. Could you tell me your opinion?

**Comment by PetroWu** [comment]
The second paper（denoted as eccv16）uses the first paper（denoted as eg16）'s network as inputs of trimap. But in eccv16, the author uses three d×d×d×d tensors to predict, while in eg16 he uses softmax to directly predict. This should be the main difference. I implemented eccv16 but the three tensors are too large that i can train it on my device.

**Comment by wanyy6** [comment]
I agree with you. The three tensors correspond to foreground, background and unknown pixels. Thanks.

**Comment by PetroWu** [comment]
The diag matrices of F/B and the Laplace matrix key of eccv16, but they are too large and it has limited contribution to the community.
