### ISSUE TITLE
Can't use the scripts " data_download.m" and  "generate_data_file.m" to download the images

### ISSUE THREAD

**Issue by zhanpx** [PetroWu/AutoPortraitMatting#36]
alldata_urls中的链接翻墙后可以打开图片，但是脚本下载图片失败，作者可以提供图片的其他下载方式吗，谢谢了！

**Comment by zhanpx** [comment]
Ok, I finished downloading these photos with proxychains , socks5 and wget cmd.

**Comment by tony-ch** [comment]
@zhanpx 能说一下详细的方法吗

**Comment by leijue222** [comment]
@zhanpx 请问怎样才能运行.m格式的文件，我没找到运行该文件的方式
