### ISSUE TITLE
这个repo的名字不好

### ISSUE THREAD

**Issue by leaf918** [PetroWu/AutoPortraitMatting#44]
实际做的事是segmentation,不是matting.

**Comment by dongwu92** [comment]
哈哈，本来想做matting的，后来发现做不下去了。。。

**Comment by phybrain** [comment]
这到底是matting还是segmentation啊

**Comment by leijue222** [comment]
Tensorflow的版本是多少啊

**Comment by dongwu92** [comment]
matting的方案没有上传，显存占用太大我的机子跑不起来，所以也没法验证是否可行。。。
