### ISSUE TITLE
MITSceneParsingData error

### ISSUE THREAD

**Issue by GirishaGarg** [PetroWu/AutoPortraitMatting#6]
Hi 
Thanks for providing the work. I am getting the following error
Traceback (most recent call last):
  File "FCN.py", line 5, in <module>
    import read_MITSceneParsingData as scene_parsing
ImportError: No module named 'read_MITSceneParsingData'
I tried commenting it, but then in order to use data, i dont see any function from the preprocess.py file being called in FCN.py or portrait.py.

**Comment by PetroWu** [comment]
Just comment it, this is useless in this task

**Comment by GirishaGarg** [comment]
Yes, I had assumed so. But I still cannot see where the gen_data function is being called from preprocess. Basically I cannot find where the data is being introduced into the code.

**Comment by PetroWu** [comment]
I've comment all the codes of data_dir flag and SceneParsing, you don't need to modify it.
Actually the data is read by 
`train_dataset_reader = BatchDatset('data/trainlist.mat')`
and BatchDatset is implemented at portrait.py and portrait_plus.py respectively.

**Comment by GirishaGarg** [comment]
I cannot see any changes. Are you sure you pushed the modifications ?

**Comment by leijue222** [comment]
@PetroWu 我配置好了所以环境并且运行起来了

> data = BatchDatset('data/trainlist.mat')
> imgs, labels = data.get_variations(47)

但是运行到这个，Imgs和labels取得的缺失一个空数组，请问这是这么回事?
是trainlist.mat文件有错误？我在您分享的百度云盘上下载的该文件，但是该文件只有3Kb
