### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by GirishaGarg** [PetroWu/AutoPortraitMatting#7]
HI,

Thanks for the help. I implemented the code, and getting the output, which I have attached. Is this what I should be getting ? If yes, how do I extract the segmented output from it? Can you help ? 
![pre0](https://cloud.githubusercontent.com/assets/12587184/22725361/f4afaf74-edf2-11e6-8d04-81797074ecf8.png)

**Comment by rubychilds** [comment]
@PetroWu would you be able to help on the above as well as running for new images - Thanks!

**Comment by rubychilds** [comment]
@GirishaGarg I believe you closed this issue, but did not answer the question. Can you assist?

**Comment by GirishaGarg** [comment]
@rubychilds I was not training the model properly. You need to train the model first with all the images and then test it on other files. You can change the number and index of files to be tested by changing the batch size and test.mat file. 

Hope it helps.

**Comment by IamMegatron2025** [comment]
@GirishaGarg  I have the same question. Can you tell me how do I extract the segmented output from it?
