### ISSUE TITLE
data/portraitFCN_data/ missing

### ISSUE THREAD

**Issue by rubychilds** [PetroWu/AutoPortraitMatting#8]
Seems the folder is data/portraitFCN_data/ is missing, even when downloading from data link.

**Comment by rubychilds** [comment]
Is used in `portrait.py` and `portrait_plus.py`
 `img_path = 'data/portraitFCN+_data/' + stp + '.mat'`

**Comment by PetroWu** [comment]
The two missing folders can be generated by the matlab codes provided on the home page of paper Automatic Portrait Segmentation for Image Stylization".

**Comment by IamMegatron2025** [comment]
@rubychilds  @PetroWu  can you share the `data/portraitFCN_data` as I can not install `matlab` softtware to generate it ? Thanks.
